import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import MainPg from './mainpg.js';
import Navbar from './navbar.js';
import Card from './Nav.js';
import Home from './home.js';
import Service from './service.js';
import Kontakt from './kontakt.js';
import Hist from './hist.js'; 
import Links from './links.js';

ReactDOM.render(<Links />, document.getElementById('links'));
ReactDOM.render(<MainPg />, document.getElementById('mainPg'));
ReactDOM.render(<Card />, document.getElementById('side'));
ReactDOM.render(<Navbar />, document.getElementById('nav'));
ReactDOM.render(< MainPg />, document.getElementById('main'));
ReactDOM.render(< Home />, document.getElementById('home'));
ReactDOM.render(< Service />, document.getElementById('service'));
ReactDOM.render(< Kontakt />, document.getElementById('kontakt'));
ReactDOM.render(< Hist />, document.getElementById('hist'));